###服务端口######
server:
  port: 10003
spring:
  application:
    name: CONFIG-CENTER
####配置中心的地址以及相关配置###############
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CHZ-LOVE/ConfigCenter.git         #git地址
          search-paths: config-repo                                 #git根路径下配置文件所在目录
          username: CHZ-LOVE                                        #用户名
          password: zeng@1995                                       #密码
####注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
      ip-address: 127.0.0.1
      prefer-ip-address: true
      instance-id: ${eureka.instance.ip-address}:${server.port}
####不设置访问权限
management:
  security:
    enabled: false