server:
  port: 9991
spring:
  application:
    name: USER-SERVER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/websocket?characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    password: redis
    timeout: 2000s
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
          defaultZone: http://127.0.0.1:10001/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
msg:
  sign:
    signName: 顾以夕沐
    templateCode: SMS_173345863
    accessKeyId: LTAIwQUYtEYnhiGz
    accessKeySecret: 9nD1IVuxjj6TEOzMyd9Sx1QVqNpn9T
###开启日志配置(使用默认配置文件、进行配置)
#logging:
#  pattern:
#    console: "%d - %msg%n"
#    file: "%d - %msg%n"
#  ###按路径保存
##  path: C:\Users\hhh\Desktop\test\
#  ##按文件名保存
#  file: C:\Users\hhh\Desktop\test\springBoot.log
#  level: debug
####文件输出
###自定义日志文件（配置文件名字自定义的、需要配置该路径）
logging:
  config: classpath:logback-spring.xml
jwt:
  info:
    expire: 30
    surplus: 10
