server:
  port: 9991
spring:
  application:
    name: USER-LOGIN
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/websocket?characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 10.16.21.69
    password: redis
    timeout: 2000s
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
          defaultZone: http://10.16.21.69:10001/eureka
  instance:
    ip-address: 10.16.21.69
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
msg:
  sign:
    signName: 顾以夕沐
    templateCode: SMS_173345863
    accessKeyId: LTAIwQUYtEYnhiGz
    accessKeySecret: 9nD1IVuxjj6TEOzMyd9Sx1QVqNpn9T
