server:
  port: 9991
spring:
  application:
    name: USER-SERVER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/websocket?characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    password: redis
    timeout: 2000s
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
          defaultZone: http://127.0.0.1:10001/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
msg:
  sign:
    signName: 顾以夕沐
    templateCode: SMS_173345863
    accessKeyId: LTAIwQUYtEYnhiGz
    accessKeySecret: 9nD1IVuxjj6TEOzMyd9Sx1QVqNpn9T
###自定义日志文件（配置文件名字自定义的、需要配置该路径）
logging:
  config: classpath:logback-spring.xml
jwt:
  info:
    expire: 30
    surplus: 10
