spring:
  application:
    name: CHAT-SERVER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf-8
    username: root
    password: root
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    ##发送ack确认发送到交换器
    publisher-confirms: true
    ##发送ack确认路由到queue队列
    publisher-returns: true
    ##监听接受时ack确认
    listener:
      simple:
        acknowledge-mode: manual
  data:
    elasticsearch:
      ##集群名称
      cluster-name: elasticsearch
      ##端口是9300（tcp\节点间交互的端口）不是9200(插件间使用的端口)
      cluster-nodes: 127.0.0.7:9300,127.0.0.1:9301
      ##是否开启本地存储
      repositories:
        enabled: true
server:
  port: 9996
ra:
  ex: boot_exchange
  key: routeKey
  ques:
    que1: boot_queue
mybatis:
  mapper-locations: classpath:mapper/*.xml

